### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by anyone0034** [gookit/validate#122]
- OS: `linux`
 - GO Version: `go1.17.2`
 - Pkg Version: `1.2.11`

我用validate验证api接口参数时，高并发情况下，出现fatal error: concurrent map iteration and map write错误，是不是和zhcn.RegisterGlobal()下的
func RegisterGlobal() {
	validate.AddGlobalMessages(Data)
}

有关啊！
我看该方法下有一个map的读写操作

```go
func AddGlobalMessages(mp map[string]string) {
	for name, msg := range mp {
		builtinMessages[name] = msg
	}
}
```

```text
fatal error: concurrent map iteration and map write

goroutine 89 [running]:
runtime.throw({0xcda682, 0x110})
   /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc00074b088 sp=0xc00074b058 pc=0x4358d1
runtime.mapiternext(0xbcd940)
   /usr/local/go/src/runtime/map.go:858 +0x4eb fp=0xc00074b0f8 sp=0xc00074b088 pc=0x40faab
github.com/gookit/validate.NewTranslator()
   /go/pkg/mod/github.com/gookit/validate@v1.2.11/messages.go:261 +0x71 fp=0xc00074b1a8 sp=0xc00074b0f8 pc=0xa09291
github.com/gookit/validate.newValidation({0x1364678, 0xc0005aa140})
   /go/pkg/mod/github.com/gookit/validate@v1.2.11/validate.go:110 +0x53 fp=0xc00074b538 sp=0xc00074b1a8 pc=0xa0f193
github.com/gookit/validate.NewValidation({0x1364678, 0xc0005aa140}, {0x0, 0x0, 0xc0004a4c10})
   /go/pkg/mod/github.com/gookit/validate@v1.2.11/validation.go:93 +0x2d fp=0xc00074b558 sp=0xc00074b538 pc=0xa14f0d
github.com/gookit/validate.(*StructData).Create(0xc0005aa140, {0xc0004a4c10, 0x1, 0xb78c40})
   /go/pkg/mod/github.com/gookit/validate@v1.2.11/data_source.go:224 +0x45 fp=0xc00074b5c8 sp=0xc00074b558 pc=0xa03385
github.com/gookit/validate.mustNewValidation({0x1364678, 0xc0005aa140}, {0x0, 0x0})
   /go/pkg/mod/github.com/gookit/validate@v1.2.11/validate.go:226 +0xcf fp=0xc00074b600 sp=0xc00074b5c8 pc=0xa10e6f
github.com/gookit/validate.Struct({0xb78c40, 0xc0004ea880}, {0x0, 0x0, 0x8})
   /go/pkg/mod/github.com/gookit/validate@v1.2.11/validate.go:210 +0x45 fp=0xc00074b630 sp=0xc00074b600 pc=0xa10d05
github.com/gookit/validate.New({0xb78c40, 0xc0004ea880}, {0x0, 0x0, 0x0})
   /go/pkg/mod/github.com/gookit/validate@v1.2.11/validate.go:189 +0x2ee fp=0xc00074b680 sp=0xc00074b630 pc=0xa10c4e

```

**Comment by inhere** [comment]
zhcn.RegisterGlobal() 你是在哪里调用的。这个应该在启动时调用一次就行

**Comment by anyone0034** [comment]
> 

goroutine内调用的，我是每个请求调用1次zhcn.RegisterGlobal()...validate.New()...我现在删除了zhcn.RegisterGlobal()就正常了。感谢！

**Comment by anyone0034** [comment]
> zhcn.RegisterGlobal() 你是在哪里调用的。这个应该在启动时调用一次就行

goroutine内调用的，我每个请求调用了1次zhcn.RegisterGlobal()...validate.New()...我现在删除了zhcn.RegisterGlobal()就正常了。感谢！
