### ISSUE TITLE
required好像不支持指针变量的校验. 

### ISSUE THREAD

**Issue by Ysclmml** [gookit/validate#78]
我使用go-playground校验器的时候, 校验零值只需要定义指针就行了, 但是这里好像不行. 下面是我的demo例子.
```go
package test

import (
	"fmt"
	"github.com/gookit/validate"
	_ "novel/bootstrap"
	"testing"
)


// UserForm struct
type UserDto struct {
	// Name     string    `validate:"required|minLen:7"`
	Name     string    `validate:"required"`
	Sex   	*bool	   `validate:"required"`
}


// Messages 您可以自定义验证器错误消息
func (ud UserDto) Messages() map[string]string {
	return validate.MS{
		"required": "oh! the {field} is required",
		"Name.required": "name 必填",
	}
}

func testValidate(ud *UserDto)  {
	// 创建 Validation 实例
	v := validate.Struct(ud)
	if !v.Validate() {
		fmt.Println(v.Errors)
	} else {
		fmt.Println("Success...")
	}
}

func TestMyValidator(t *testing.T)  {
	sex := true
	u := UserDto{
		// Name: "inhere",
		Name: "abc",
		Sex: &sex,
	}
	testValidate(&u)
	// 下面如果Sex不传或传nil, 会panic错误
	testValidate(&UserDto{
		Name: "abc",
		Sex: nil,
	})
}

请问该如何解决零值的校验问题呢?

**Comment by fishyww** [comment]
我尝试去复现你所描述的问题，但是并没有发生panic，测试结果如下：
```go
=== RUN   TestMyValidator
Success...
Sex:
 required: oh! the Sex is required
--- PASS: TestMyValidator (0.00s)
PASS
```
我认为这不是一个bug， `validate:"required"` 的意思是验证字段是有值，传nil等于没有值，验证不通过。
你可能需要这样：
```go
sex := false
u := UserDto{
	// Name: "inhere",
	Name: "abc",
	Sex: &sex,
}
```
再举例说一下：
```go
type UserDto struct {
	...
	Age *int `validate:"required"`
       ...
}
...
age:= 0
u := UserDto{
	Age: &age,
}
```

**Comment by Ysclmml** [comment]
> 我尝试去复现你所描述的问题，但是并没有发生panic，测试结果如下：
> 
> ```go
> === RUN   TestMyValidator
> Success...
> Sex:
>  required: oh! the Sex is required
> --- PASS: TestMyValidator (0.00s)
> PASS
> ```
> 
> 我认为这不是一个bug， `validate:"required"` 的意思是验证字段是有值，传nil等于没有值，验证不通过。
> 你可能需要这样：
> 
> ```go
> sex := false
> u := UserDto{
> 	// Name: "inhere",
> 	Name: "abc",
> 	Sex: &sex,
> }
> ```
> 
> 再举例说一下：
> 
> ```go
> type UserDto struct {
> 	...
> 	Age *int `validate:"required"`
>        ...
> }
> ...
> age:= 0
> u := UserDto{
> 	Age: &age,
> }
> ```

```go
func TestMyValidator(t *testing.T)  {
	// 下面如果Sex不传或传nil, 会panic错误
	sex := false
	testValidate(&UserDto{
		Name: "abc",
		Sex: &sex,
	})
	fmt.Println("=============")
	testValidate(&UserDto{
		Name: "abc",
		Sex: nil,
	})
}
```
可是我的机器上是会报panic错误的,下面是运行结果
```go
=== RUN   TestMyValidator
Sex:
 required: oh! the Sex is required
=============
--- FAIL: TestMyValidator (0.00s)
panic: reflect: call of reflect.Value.CanInterface on zero Value [recovered]
	panic: reflect: call of reflect.Value.CanInterface on zero Value

goroutine 194 [running]:
testing.tRunner.func1.1(0xd57640, 0xc000372260)
	/usr/local/go/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000a20180)
	/usr/local/go/src/testing/testing.go:1075 +0x41a
panic(0xd57640, 0xc000372260)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
reflect.Value.CanInterface(...)
	/usr/local/go/src/reflect/value.go:1005
github.com/gookit/validate.(*StructData).Get(0xc00036e500, 0xce6c68, 0x3, 0x3, 0x156ac60, 0x0)
	/home/yscl/go/pkg/mod/github.com/gookit/validate@v1.2.5/data_source.go:409 +0x491
github.com/gookit/validate.(*Validation).Get(0xc0004903c0, 0xce6c68, 0x3, 0xa, 0xffffffffffffffff, 0xe5226b)
	/home/yscl/go/pkg/mod/github.com/gookit/validate@v1.2.5/validation.go:370 +0xfc
github.com/gookit/validate.(*Validation).GetWithDefault(...)
	/home/yscl/go/pkg/mod/github.com/gookit/validate@v1.2.5/validation.go:377
github.com/gookit/validate.(*Rule).Apply(0xc000490540, 0xc0004903c0, 0xc00036e500)
	/home/yscl/go/pkg/mod/github.com/gookit/validate@v1.2.5/validating.go:97 +0x4fb
github.com/gookit/validate.(*Validation).Validate(0xc0004903c0, 0x0, 0x0, 0x0, 0x0)
	/home/yscl/go/pkg/mod/github.com/gookit/validate@v1.2.5/validating.go:45 +0x106
novel/test.testValidate(0xc0003721c0)
	/home/yscl/Project/Personal/go/novel/test/validator2_test.go:30 +0x70
novel/test.TestMyValidator(0xc000a20180)
	/home/yscl/Project/Personal/go/novel/test/validator2_test.go:45 +0x115
testing.tRunner(0xc000a20180, 0xe8e740)
	/usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x2b3
```

**Comment by fishyww** [comment]
我知道问题了，拉取最新代码就复现，我尝试一下能否解决这个问题哈

**Comment by inhere** [comment]
@Ysclmml  发了新版本，再试试看呢
